spring.application.name=graduation-work

spring.datasource.url=jdbc:postgresql://localhost:8081/online_shop_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.web.resources.static-locations=classpath:/static/


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.drop-first=false
spring.liquibase.default-schema=public